ParrotdiseShop.Web/Areas/Admin/Controllers/ApplicationUsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ParrotdiseShop.Core.Utilities;

namespace ParrotdiseShop.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = RoleName.Admin)]
    public class ApplicationUsersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ParrotdiseShop.Web/Areas/Admin/Controllers/OrdersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ParrotdiseShop.Core;
using ParrotdiseShop.Core.Dtos;
using ParrotdiseShop.Core.Models;
using ParrotdiseShop.Core.Utilities;
using ParrotdiseShop.Core.ViewModels;

namespace ParrotdiseShop.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
	[Authorize]
	public class OrdersController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly IMapper _mapper;

		public OrdersController(IUnitOfWork unitOfWork, IMapper mapper)
		{
			_unitOfWork = unitOfWork;
			_mapper = mapper;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Details(int id)
		{
			var order = _unitOfWork.Orders.GetOrderDetailsWithUser(id);

			if (order == null)
				return NotFound();

			var viewModel = new OrderViewModel
			{ 
				Order = _mapper.Map<OrderDto>(order),
				OrderDetails = _mapper.Map<IEnumerable<OrderDetailDto>>(_unitOfWork.OrderDetails.GetOrderDetailsWithProductBy(order.Id)),
				Provinces = CanadianProvinces.Provinces
			};

			if (User.IsInRole(RoleName.Customer))
				return View("ViewOrderDetails", viewModel);
			else
				return View("UpdateOrderDetails", viewModel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = $"{RoleName.Admin},{RoleName.Employee}")]
		public IActionResult UpdateCustomerInformation(OrderViewModel viewModel)
		{
			var orderFromDb = _unitOfWork.Orders.Get(o => o.Id == viewModel.Order.Id);

			if (orderFromDb == null)
				return NotFound();

			var order = _mapper.Map<Order>(viewModel.Order);
			orderFromDb.UpdateCustomerInformation(order);

			_unitOfWork.Complete();

			TempData["info"] = "Customer Information updated successfully";

			return RedirectToAction(nameof(Details), new { id = viewModel.Order.Id });
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Authorize(Roles = $"{RoleName.Admin},{RoleName.Employee}")]
		public IActionResult Process(OrderViewModel viewModel)
		{
			var orderFromDb = _unitOfWork.Orders.Get(o => o.Id == viewModel.Order.Id);

			if (orderFromDb == null)
				return NotFound();

			orderFromDb.UpdateStatus(OrderStatus.StatusProcessing);
			_unitOfWork.Complete();

			return RedirectToAction(nameof(Details), new { id = viewModel.Order.Id });
		}

		[HttpPost]
		[Authorize(Roles = $"{RoleName.Admin},{RoleName.Employee}")]
		public IActionResult Ship(OrderViewModel viewModel)
		{
			var orderFromDb = _unitOfWork.Orders.Get(o => o.Id == viewModel.Order.Id);

			if (orderFromDb == null)
				return NotFound();

			orderFromDb.UpdateShippingInformation(viewModel.Order.Carrier, viewModel.Order.TrackingNumber);
			
			_unitOfWork.Complete();

			return RedirectToAction(nameof(Details), new { id = viewModel.Order.Id });
		}

		[HttpPost]
        [Authorize(Roles = $"{RoleName.Admin},{RoleName.Employee}")]
        public IActionResult Cancel(int id)
        {
            var orderFromDb = _unitOfWork.Orders.Get(o => o.Id == id);

            if (orderFromDb == null)
                return NotFound();

            orderFromDb.UpdateStatus(OrderStatus.StatusCancelled);
            _unitOfWork.Complete();

            return RedirectToAction(nameof(Details), new { id });
        }
    }
}

ParrotdiseShop.Web/Areas/Admin/Controllers/ProductsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ParrotdiseShop.Core;
using ParrotdiseShop.Core.Dtos;
using ParrotdiseShop.Core.Models;
using ParrotdiseShop.Core.Utilities;
using ParrotdiseShop.Core.ViewModels;
using System.Data;
using System.Reflection;

namespace ParrotdiseShop.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = $"{RoleName.Admin},{RoleName.Employee}")]
    public class ProductsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IMapper _mapper;

        public ProductsController(IUnitOfWork unitOfWork, IMapper mapper, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult New()
        {
            var categories = _unitOfWork.Categories
                                    .GetAll()
                                    .Select(c => new SelectListItem 
                                    { 
                                        Text = c.Name, 
                                        Value = c.Id.ToString() }
                                    );

            var viewModel = new ProductFormViewModel
            {
                Categories = categories,
                Heading = MethodBase.GetCurrentMethod().Name,
                IsEdit = false
            };

            return View("ProductForm", viewModel);
        }

        public IActionResult Edit(int id)
        {
            var productFromDb = _unitOfWork.Products.Get(c => c.Id == id);

            if (productFromDb == null)
                return NotFound();

            var categories = _unitOfWork.Categories
                                    .GetAll()
                                    .Select(c => new SelectListItem
                                    {
                                        Text = c.Name,
                                        Value = c.Id.ToString()
                                    });

            var viewModel = new ProductFormViewModel
            {
                Product = _mapper.Map<ProductDto>(productFromDb),
                Categories = categories,
                Heading = MethodBase.GetCurrentMethod().Name,
                IsEdit = true
            };

            return View("ProductForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save(ProductFormViewModel viewModel, IFormFile? file)
        {
            if (!ModelState.IsValid)
            {
                var categories = _unitOfWork.Categories
                                        .GetAll()
                                        .Select(c => new SelectListItem
                                        {
                                            Text = c.Name,
                                            Value = c.Id.ToString()
                                        });

                viewModel.Categories = categories;
                return View("ProductForm", viewModel);
            }

            var productDto = viewModel.Product;

            if (file != null)
            {
                var uploadPath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\products");

                if (productDto.ImagePath != null)
                {
                    string oldFileName = Path.GetFileName(productDto.ImagePath);
                    string oldFilePath = Path.Combine(uploadPath, oldFileName);

                    if (System.IO.File.Exists(oldFilePath))
                        System.IO.File.Delete(oldFilePath);
                }

                var newFileName = Guid.NewGuid().ToString();

                var extension = Path.GetExtension(file.FileName);

                using var fileStream = new FileStream(Path.Combine(uploadPath, newFileName + extension), FileMode.Create);
                file.CopyTo(fileStream);

                productDto.ImagePath = @"\images\products\" + newFileName + extension;
            }

            if (productDto.Id == 0)
            {
                _unitOfWork.Products.Add(_mapper.Map<Product>(productDto));
                _unitOfWork.Complete();

                TempData["success"] = "Product created successfully";
            }
            else
            {
                var productFromDb = _unitOfWork.Products.Get(p => p.Id == productDto.Id);

                if (productFromDb == null)
                    return NotFound();

                _mapper.Map(productDto, productFromDb);
                
                _unitOfWork.Complete();

                TempData["success"] = "Product updated successfully";
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ParrotdiseShop.Web/Controllers/CategoriesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ParrotdiseShop.Core;
using ParrotdiseShop.Core.Dtos;
using ParrotdiseShop.Core.Models;
using ParrotdiseShop.Core.ViewModels;
using ParrotdiseShop.Persistence.Data;
using System.Reflection;

namespace ParrotdiseShop.Web.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public CategoriesController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult New()
        {
            var viewModel = new CategoryFormViewModel
            {
                CategoryDto = new(),
                Heading = MethodBase.GetCurrentMethod().Name,
                IsEdit = true
            };

            return View("CategoryForm", viewModel);
        }

        public IActionResult Edit(int id)
        {
            var categoryFromDb = _unitOfWork.Categories.Get(c => c.Id == id);

            if (categoryFromDb == null)
                return NotFound();

            var categoryDto = _mapper.Map<CategoryDto>(categoryFromDb);

            var viewModel = new CategoryFormViewModel 
            {
                CategoryDto = categoryDto,
                Heading = MethodBase.GetCurrentMethod().Name,
                IsEdit = true
            };

            return View("CategoryForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save(CategoryFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("CategoryForm", viewModel);

            var categoryDto = viewModel.CategoryDto;


            if (categoryDto.Id == 0)
            {
                var category = _mapper.Map<Category>(categoryDto);
                _unitOfWork.Categories.Add(category);
                _unitOfWork.Complete();

                TempData["success"] = "Product created successfully";
            }
            else
            {
                var categoryInDb = _unitOfWork.Categories.Get(c => c.Id == categoryDto.Id);

                if (categoryInDb == null)
                    return NotFound();

                _mapper.Map(categoryDto, categoryInDb);
                _unitOfWork.Complete();

                TempData["success"] = "Product updated successfully";
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ParrotdiseShop.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Parrotdise Shop</title>
    <link rel="stylesheet" href="~/css/bootstrap-minty.css" />
    @*<link rel="stylesheet" href="~/ParrotdiseShop.Web.styles.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index"><img src="~/images/parrots/GreenCheekConure_Cocomo.png" title="This is an image of our pet green cheek conure named Cocomo" style="width:30px" />&nbsp;Parrotdise Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="Customer" asp-controller="Home" asp-action="Index">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Manage</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Orders" asp-action="Index">Orders</a>

                                    @if (User.IsInRole(RoleName.Admin) 
                                        || User.IsInRole(RoleName.Employee))
                                    {
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Categories" asp-action="Index">Categories</a>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a>
                                    }

                                    <div class="dropdown-divider"></div>

                                    @if (User.IsInRole(RoleName.Admin))
                                    {
                                        @*<a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create New User</a>*@
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="ApplicationUsers" asp-action="Index">Users</a>
                                    }
                                </div>
                            </li>
                        }

                        <li class="nav-item cart-counter">
                            <a class="nav-link" asp-area="Customer" asp-controller="ShoppingCartItems" asp-action="Index">
                                <i class="bi bi-cart"></i>
                                <span class="invisible badge js-cart-count"></span>
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-white">
        <div class="container">
            Demo Project Made By - <a href="https://www.linkedin.com/in/saira-rashid1216/" target="_blank">Saira Rashid</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.tiny.cloud/1/u04m9oqys95zwduqn4l3khifi5egu5u6p2fkb411y7lg3jah/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script>
        $(function () {
            $.get("/customer/api/ShoppingCartItems", function (noOfShoppingCartItems) {
                if (noOfShoppingCartItems === 0)
                    return;

                let badge = $('.js-cart-count');
                badge
                    .text(noOfShoppingCartItems)
                    .removeClass('invisible')
            });
        });
    </script>
</body>
</html>

ParrotdiseShop.Web/Views/Shared/_Notification.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

@if (TempData["success"] != null)
{
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if (TempData["error"] != null)
{
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}

@if (TempData["info"] != null)
{
    <script type="text/javascript">
        toastr.info('@TempData["info"]');
    </script>
}