ParrotdiseShop.Web/Areas/Customer/Controllers/ShoppingCartItemsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ParrotdiseShop.Core;
using ParrotdiseShop.Core.Dtos;
using ParrotdiseShop.Core.Models;
using ParrotdiseShop.Core.Utilities;
using ParrotdiseShop.Core.ViewModels;
using Stripe.Checkout;

namespace ParrotdiseShop.Web.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class ShoppingCartItemsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ShoppingCartItemsController(IUnitOfWork unitOfWork, IMapper mapper, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            IEnumerable<ShoppingCartItem> shoppingCartItems;

            if (User.Identity.IsAuthenticated)
            {
                var userId = User.GetUserId();

                shoppingCartItems = _unitOfWork.ShoppingCartItems
                                        .GetAllShoppingCartItemsWithProductsByUser(userId);
            }
            else
            {
                var guestCookieId = Request.Cookies["ShoppingCart"];

                shoppingCartItems = _unitOfWork.ShoppingCartItems
                                        .GetAllShoppingCartItemsWithProductsByCookie(guestCookieId);
            }

            var viewModel = new ShoppingCartViewModel
            {
                ShoppingCartItems = _mapper.Map<IEnumerable<ShoppingCartItemDto>>(shoppingCartItems)
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult IncrementQuantity(int id)
        {
            var shoppingCartItemFromDb = _unitOfWork.ShoppingCartItems.GetShoppingCartItemWithProduct(id);

            if (shoppingCartItemFromDb == null)
                return NotFound();

            if (shoppingCartItemFromDb.Product.UnitsInStock == 0)
                ModelState.AddModelError("", 
                    $"{shoppingCartItemFromDb.Product.Name} is now out of stock. Please remove from cart to proceed to checkout");
            else if (shoppingCartItemFromDb.Quantity > shoppingCartItemFromDb.Product.UnitsInStock)
                ModelState.AddModelError("", 
                    $"{shoppingCartItemFromDb.Product.Name} is running low on stock. Please reduce quantity.");
            else if (shoppingCartItemFromDb.Quantity == shoppingCartItemFromDb.Product.UnitsInStock)
                ModelState.AddModelError("",
                    $"You have reached max. limit. Cannot add more quantity of {shoppingCartItemFromDb.Product.Name}");

            if (!ModelState.IsValid)
                return RedirectToAction(nameof(Index));

            shoppingCartItemFromDb.Increment(1);
            _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DecrementQuantityOrRemove(int id)
        {
            var shoppingCartItemFromDb = _unitOfWork.ShoppingCartItems.Get(sc => sc.Id == id);

            if (shoppingCartItemFromDb == null)
                return NotFound();

            // Remove shopping Cart Item from Shopping Cart
            if (shoppingCartItemFromDb.Quantity == 1)
                _unitOfWork.ShoppingCartItems.Remove(shoppingCartItemFromDb);
            else
                shoppingCartItemFromDb.Decrement();

            _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Remove(int id)
        {
            var shoppingCartItemFromDb = _unitOfWork.ShoppingCartItems.Get(sc => sc.Id == id);

            if (shoppingCartItemFromDb == null)
                return NotFound();

            _unitOfWork.ShoppingCartItems.Remove(shoppingCartItemFromDb);
            _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public IActionResult Checkout()
        {
            var userId = User.GetUserId();

            TransferGuestShoppingCartToCustomerAccount(userId);

            var shoppingCartItems = _unitOfWork.ShoppingCartItems
                                        .GetAllShoppingCartItemsWithProductsByUser(userId);

            //nothing to checkout
            if (!shoppingCartItems.Any())
                return NotFound();

            var viewModel = new ShoppingCartViewModel
            {
                ShoppingCartItems = _mapper.Map<IEnumerable<ShoppingCartItemDto>>(shoppingCartItems)
            };

            if (!viewModel.IsValid)
                return RedirectToAction(nameof(Index));

            var customer = _unitOfWork.ApplicationUsers.Get(u => u.Id == userId);

            if (customer == null)
                return NotFound();

            viewModel.Order = _mapper.Map<OrderDto>(new Order(customer));
            viewModel.Provinces = CanadianProvinces.Provinces;

            return View(viewModel);
        }

        public IActionResult CheckoutChoice()
        {
            // give end users the choice to login or continue as guest
            return View();
        }

        public IActionResult CheckoutAsGuest()
        {
            var guestCookieId = Request.Cookies["ShoppingCart"];

            var shoppingCartItems = _unitOfWork.ShoppingCartItems
                                        .GetAllShoppingCartItemsWithProductsByCookie(guestCookieId);

            if (!shoppingCartItems.Any())
                return NotFound();

            var viewModel = new ShoppingCartViewModel
            {
                ShoppingCartItems = _mapper.Map<IEnumerable<ShoppingCartItemDto>>(shoppingCartItems)
            };

            if (!viewModel.IsValid)
                return RedirectToAction(nameof(Index));

            viewModel.Order = _mapper.Map<OrderDto>(new Order());
            viewModel.Provinces = CanadianProvinces.Provinces;

            return View(nameof(Checkout), viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult PlaceOrder(ShoppingCartViewModel viewModel)
        {
            IEnumerable<ShoppingCartItem> shoppingCartItems;

            if (User.Identity.IsAuthenticated)
                shoppingCartItems = _unitOfWork.ShoppingCartItems
                                        .GetAllShoppingCartItemsWithProductsByUser(User.GetUserId());
            else
                shoppingCartItems = _unitOfWork.ShoppingCartItems
                                                .GetAllShoppingCartItemsWithProductsByCookie(Request.Cookies["ShoppingCart"]); 
            
            if (!shoppingCartItems.Any())
                return NotFound();

            viewModel.ShoppingCartItems = _mapper.Map<IEnumerable<ShoppingCartItemDto>>(shoppingCartItems);

            if (!viewModel.IsValid)
                return RedirectToAction(nameof(Index));

            var order = _mapper.Map<Order>(viewModel.Order);
            
            if (User.Identity.IsAuthenticated)
                order.Create(User.GetUserId(), null, viewModel.Total);
            else
                order.Create(null, Request.Cookies["ShoppingCart"], viewModel.Total);

            _unitOfWork.Orders.Add(order);
            _unitOfWork.Complete();

            foreach (var item in viewModel.ShoppingCartItems)
            {
                var orderDetail = new OrderDetail
                {
                    OrderId = order.Id,
                    ProductId = item.ProductId,
                    Quantity = item.Quantity,
                    Price = item.Product.UnitPrice
                };

                _unitOfWork.OrderDetails.Add(orderDetail);
            }

            _unitOfWork.Complete();

            #region Stripe Settings

            var domain = @$"{Request.Scheme}://{Request.Host.Value}/";

			var options = new SessionCreateOptions
			{
				LineItems = new List<SessionLineItemOptions>(),
				Mode = "payment",
				SuccessUrl = $"{domain}customer/ShoppingCartItems/OrderConfirmation?id={order.Id}",
				CancelUrl = $"{domain}customer/ShoppingCartItems/Index"
			};

			foreach (var item in viewModel.ShoppingCartItems)
			{
				var sessionLineItem = new SessionLineItemOptions
				{
					PriceData = new SessionLineItemPriceDataOptions
					{
						UnitAmount = (long)(item.Product.UnitPrice * 100),
						Currency = "usd",
						ProductData = new SessionLineItemPriceDataProductDataOptions
						{
							Name = item.Product.Name
						}
					},
					Quantity = item.Quantity
				};

				options.LineItems.Add(sessionLineItem);
			}

			var service = new SessionService();
			Session session = service.Create(options);

            order.UpdateStripeSessionId(session.Id);

			_unitOfWork.Complete();

			Response.Headers.Add("Location", session.Url);

			return new StatusCodeResult(303);

			#endregion
        }

        public IActionResult OrderConfirmation(int id)
        {
			var order = _unitOfWork.Orders.GetOrderDetailsWithUser(id);

			if (order == null)
				return NotFound();

			var service = new SessionService();
			var session = service.Get(order.PaymentSessionId);

			// check the stripe status
			if (session.PaymentStatus.ToLower() == "paid")
			{
				order.UpdateStripePaymentId(session.PaymentIntentId);
				order.UpdateStatus(OrderStatus.StatusApproved, OrderStatus.PaymentStatusApproved);
				_unitOfWork.Complete();
			}

            IEnumerable<ShoppingCartItem> shoppingCartItems;

            // Get shopping cart from db using cookie id if guest user or user id 
            // if user is logged in 
            if (User.Identity.IsAuthenticated)

ParrotdiseShop.Web/Areas/Customer/Controllers/api/ShoppingCartItemsController.cs
using Microsoft.AspNetCore.Mvc;
using ParrotdiseShop.Core;
using ParrotdiseShop.Core.Models;
using ParrotdiseShop.Core.Utilities;
using System.Security.Claims;

namespace ParrotdiseShop.Web.Areas.Customer.Controllers.api
{
    [Route("/customer/api/[controller]")]
    [ApiController]
    [Area("Customer")]
    public class ShoppingCartItemsController : ControllerBase
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartItemsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        
        public IActionResult GetNoOfItemsInShoppingCart()
        {
            IEnumerable<ShoppingCartItem> shoppingCartItems;

            if (User.Identity.IsAuthenticated)
            {
                var userId = User.GetUserId();
                TransferGuestShoppingCartToCustomerAccount(userId);

                shoppingCartItems = _unitOfWork.ShoppingCartItems
                                        .GetAllShoppingCartItemsWithProductsByUser(userId);
            }
            else
            {
                var guestCookieId = Request.Cookies["ShoppingCart"];

                shoppingCartItems = _unitOfWork.ShoppingCartItems
                                        .GetAllShoppingCartItemsWithProductsByCookie(guestCookieId);
            }

            return Ok(shoppingCartItems.Count());
        }

        private void TransferGuestShoppingCartToCustomerAccount(string userId)
        {
            var guestCookieId = Request.Cookies["ShoppingCart"];

            if (guestCookieId == null)
                return;

            var shoppingCartItems = _unitOfWork.ShoppingCartItems
                                        .GetAllShoppingCartItemsWithProductsByCookie(guestCookieId);
            foreach (var item in shoppingCartItems)
                item.UpdateUserId(userId);

            _unitOfWork.Complete();

            Response.Cookies.Delete("ShoppingCart");
        }
    }
}

ParrotdiseShop.Web/Areas/Customer/Views/ShoppingCartItems/Checkout.cshtml
@model ShoppingCartViewModel;
@{
	ViewData["Title"] = "Checkout";
	var disabled = (User.Identity.IsAuthenticated) ? true : false;
}

<form method="post" asp-action="PlaceOrder">
	<input hidden asp-for="Total" />
	<div class="card shadow border-0 mt-4">
		<div class="card-header bg-info bg-gradient text-light py-4">
			<div class="row">
				<div class="col-12 text-center">
					<h3 class="text-white text-uppercase">
						Checkout
					</h3>
				</div>
			</div>
		</div>
			<div class="card-body">
				<div class="row pb-4">
						<div class="col-12 text-end">
							<a asp-action="Index" class="btn btn-outline-secondary fw-bold text-uppercase btn-sm">Back to Shopping Cart</a>
						</div>
					</div>
				<div class="row">
						<div class="col-12 col-lg-6 pb-2">
							<div class="row">
								<h4 class="d-flex justify-content-between align-items-center mb-3">
									<span class="text-info">Shipping Details:</span>
								</h4>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label asp-for="Order.Name">Name</label>
								</div>
								<div class="col-9">
									<input asp-for="Order.Name" class="form-control" />
									<span asp-validation-for="Order.Name" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label asp-for="Order.Email">Email</label>
								</div>
								<div class="col-9">
									<input asp-for="Order.Email" class="form-control" disabled=@disabled />
									<span asp-validation-for="Order.Email" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label asp-for="Order.PhoneNumber">Phone</label>
								</div>
								<div class="col-9">
									<input asp-for="Order.PhoneNumber" class="form-control" />
									<span asp-validation-for="Order.PhoneNumber" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label asp-for="Order.StreetAddress">Street Address</label>
								</div>
								<div class="col-9">
									<input asp-for="Order.StreetAddress" class="form-control" />
									<span asp-validation-for="Order.StreetAddress" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label asp-for="Order.City">City</label>
								</div>
								<div class="col-9">
									<input asp-for="Order.City" class="form-control" />
									<span asp-validation-for="Order.City" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label asp-for="Order.Province">Province</label>
								</div>
								<div class="col-9">
									<select asp-for="Order.Province" asp-items="@Model.Provinces" class="form-select">
										<option disabled selected>Please select one</option>
									</select>
									<span asp-validation-for="Order.Province" class="text-danger"></span>
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label asp-for="Order.PostalCode">Postal Code</label>
								</div>
								<div class="col-9">
									<input asp-for="Order.PostalCode" class="form-control" />
									<span asp-validation-for="Order.PostalCode" class="text-danger"></span>
								</div>
							</div>
						</div>
						<div class="col-12 col-lg-5 offset-lg-1">
							<h4 class="d-flex justify-content-between align-items-center mb-3">
								<span class="text-info">Order Summary:</span>
							</h4>
							<ul class="list-group mb-3">
								@foreach (var item in Model.ShoppingCartItems)
								{
									<li class="list-group-item d-flex justify-content-between">
										<div>
											<h6 class="my-0">@item.Product.Name</h6>
											<small class="text-muted">Quantity: @item.Quantity</small>
										</div>
										<span class="text-muted">@((item.Product.UnitPrice * item.Quantity).ToString("c"))</span>
									</li>
								}

								<li class="list-group-item d-flex justify-content-between bg-light">
									<small class="text-info">Total</small>
									<strong class="text-info">@Model.Total.ToString("c")</strong>
								</li>
							</ul>
						</div>
					</div>
			</div>
			<div class="card-footer bg-white border-0 p-0 pe-4">
				<div class="row">
					<div class="col-3 offset-9 mb-3">
						<button type="submit" value="Place Order" class="btn btn-primary form-control text-uppercase fw-semibold bg-gradient">Place Order</button>
					</div>
				</div>
		</div>
		</div>
</form>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

ParrotdiseShop.Web/Areas/Customer/Views/ShoppingCartItems/CheckoutChoice.cshtml
@{
	ViewData["Title"] = "How to Checkout?";
}


<div class="container">
    <div class="card shadow border-0 mt-4">
        <div class="card-header bg-info bg-gradient text-light py-4">
            <div class="row">
                <div class="col-12 text-center">
                    <h3 class="text-white text-uppercase">
                        Checkout
                    </h3>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="container overflow-hidden text-center">
                <div class="row gx-5">
                    <div class="col">
                        <div class="p-3">
                            <a asp-controller="ShoppingCartItems" asp-action="CheckoutAsGuest" class="btn btn-lg btn-outline-primary">
                                Checkout As Guest
                            </a>
                        </div>
                    </div>
                    <div class="col">
                        <div class="p-3">
                            <a asp-controller="ShoppingCartItems" asp-action="Checkout" class="btn btn-lg btn-outline-primary">
                                Login Or Create Account
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ParrotdiseShop.Web/Areas/Customer/Views/ShoppingCartItems/Index.cshtml
@model ShoppingCartViewModel

@{
    ViewData["Title"] = "Shopping Cart";
}
<form method="post">
    <div class="card shadow border-0 mt-4">
        <div class="card-header bg-info bg-gradient text-light py-4">
            <div class="row">
                <div class="col-12 text-center">
                    <h3 class="text-white text-uppercase">
                        Shopping Cart
                    </h3>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="row mb-1 pb-1">
                <div class="col-md-2 offset-md-1 my-4">
                    <a asp-controller="Home" asp-action="Index" class="btn btn-outline-secondary fw-bold btn-sm text-uppercase">
                        <span class="small">Continue Shopping</span>
                    </a>
                </div>
                @foreach (var item in Model.ShoppingCartItems)
                {
                    <div class="col-md-10 offset-md-1">
                        <div class="row border-bottom pb-1">
                            <div class="d-none d-lg-block col-lg-1 text-center py-2">
                                <img src="@item.Product.ImagePath" class="rounded img-fluid" />
                            </div>
                            <div class="col-12 col-lg-6 pt-md-3">
                                <h5 class="text-dark text-opacity-50"><strong>@item.Product.Name</strong></h5>
                                <p><small>@Html.Raw(item.Product.Description)</small></p>
                            </div>
                            <div class="col-12  col-lg-5 text-center row">
                                <div class="col-3 text-md-right pt-2 pt-md-4">
                                    <h6 class="fw-semibold">
                                        @item.Product.UnitPrice.ToString("c")
                                        <span class="text-muted">&nbsp;x&nbsp;</span>@item.Quantity
                                    </h6>
                                </div>
                                <div class="col-6 col-sm-4 col-lg-6 pt-2">
                                    <div class="w-75 btn-group" role="group">
                                        @if (item.Product.UnitsInStock > 0)
                                        {
                                            @if (item.Quantity < item.Product.UnitsInStock)
                                            {
                                                <button asp-action="IncrementQuantity" asp-route-id="@item.Id" class="btn btn-outline-primary bg-gradient py-2">
                                                    <i class="bi bi-plus-square"></i>
                                                </button>
                                            }
                                            else if (item.Quantity == item.Product.UnitsInStock)
                                            {
                                                // Cannot add more items than currently in stock
                                                <button disabled data-toggle="tooltip" title="Reached max. limit of items to be added" class="btn btn-outline-primary bg-gradient py-2 disabled stretched-link">
                                                    <i class="bi bi-plus-square"></i>
                                                </button>
                                            }
                                            else
                                            {
                                                // Added more items than currently in stock, will have to reduce quantity
                                                <button disabled data-toggle="tooltip" title="This item is running low on stock. Please reduce quantity." class="btn btn-outline-primary bg-gradient py-2 disabled stretched-link">
                                                    <i class="bi bi-plus-square"></i>
                                                </button>
                                            }

                                            <button asp-action="DecrementQuantityOrRemove" asp-route-id="@item.Id" class="btn btn-outline-primary bg-gradient py-2">
                                                <i class="bi bi-dash-square"></i>
                                            </button>
                                        }
                                        else
                                        {
                                            // Disable the option to increment/decrement quantity if items no longer in stock
                                            <p class="text-danger">Item now out of stock. Please remove from cart to checkout</p>
                                        }
                                    </div>
                                </div>
                                <div class="col-3 col-sm-4 col-lg-2 offset-lg-1 text-right pt-2">
                                    <button data-toggle="tooltip" title="Click to Remove" asp-action="Remove" asp-route-id="@item.Id" class="btn btn-danger bg-gradient py-2 ">
                                        <i class="bi bi-trash-fill"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        
        <div class="card-footer bg-white border-0">
                @if (Model.ShoppingCartItems.Any() && Model.IsValid)
                {
                    @*Display shopping cart details only if 1 or more items in shopping cart and all products are in stock*@
                    <div class="row">
                        <div class="col-md-3 offset-md-7">
                            <ul class="list-group mb-2">
                                <li class="d-flex justify-content-between align-items-center">
                                    <p class="text-info fw-semibold text-uppercase fs-6">Total</p>
                                    <p class="text-info fw-bolder fs-6">@Model.Total.ToString("c")</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                <div class="row">
                    <div class="col-md-3 offset-md-7">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <button asp-controller="ShoppingCartItems" asp-action="Checkout" class="btn btn-primary border-0 bg-gradient w-100 py-2 fw-semibold text-uppercase">Checkout</button>
                        }
                        else
                        {
                            <button asp-controller="ShoppingCartItems" asp-action="CheckoutChoice" class="btn btn-primary border-0 bg-gradient w-100 py-2 fw-semibold text-uppercase">Checkout</button>
                        }
                    </div>
                    </div>
                }
                else if (!Model.ShoppingCartItems.Any())
                {
                    <div class="row">
                        <p class="col-2 offset-5 fw-semibold text-danger">Shopping cart is empty.</p>
                    </div>
                }
                else
                {
                    <div class="row">
                        <p class="col-11 offset-2 fw-semibold text-danger">Some items are running low on stock, or out of stock. Please remove from cart to proceed to checkout.</p>
                    </div>
                }
        </div>
    </div>
</form>

ParrotdiseShop.Web/Areas/Customer/Views/ShoppingCartItems/OrderConfirmation.cshtml
@model OrderViewModel

@{
	ViewData["Title"] = "Order Confirmation";
}

<div class="container row mt-4">
	<div class="col-8 text-end">
		<span class="h2 text-info text-center">Order Placed Successfully!</span>
	</div>
	<div class="col-4 text-end noprint">
		<a onclick="window.print()" class="btn btn-outline-secondary fw-bold text-uppercase btn-sm">Print Confirmation</a>
	</div>
	<div class="row mt-4">
		<div class="col-12 text-centre">
		</div>
	</div>
	<div class="test test-contain noprint">
		<img src="~/images/parrots/Cocomo_in_the_park.png" title="This is an image of our pet green cheek conure named Cocomo"/>
	</div>
	<div class="row mt-4 mb-5">
		<div class="col-6">
			<h4 class="d-flex justify-content-between align-items-center mb-3">
				<span class="text-info">Shipping Details:</span>
			</h4>

			<div class="row">
				<div class="col-12">
					<strong>Order Number:</strong> @Model.Order.Id
				</div>
			</div>

			<div class="row">
				<div class="col-12">
					<strong>Name:</strong> @Model.Order.Name
				</div>
			</div>

			<div class="row">
				<div class="col-12">
					<strong>Phone:</strong> @Model.Order.PhoneNumber
				</div>
			</div>

			<div class="row">
				<div class="col-12">
					<strong>Street Address:</strong> @Model.Order.StreetAddress
				</div>
			</div>

			<div class="row">
				<div class="col-12">
					<strong>City:</strong> @Model.Order.City
				</div>
			</div>

			<div class="row">
				<div class="col-12">
					<strong>Province:</strong> @Model.Order.Province
				</div>
			</div>

			<div class="row">
				<div class="col-12">
					<strong>Postal Code:</strong> @Model.Order.PostalCode
				</div>
			</div>
		</div>
		<div class="col-6">
			<h4 class="d-flex justify-content-between align-items-center mb-3">
				<span class="text-info">Order Summary:</span>
			</h4>

			<ul class="list-group mb-3">
				@foreach (var item in Model.OrderDetails)
				{
					<li class="list-group-item d-flex justify-content-between">
						<div>
							<h6 class="my-0">@item.Product.Name</h6>
							<small class="text-muted">Quantity: @item.Quantity</small>
						</div>
						<span class="text-muted">@((item.Product.UnitPrice * item.Quantity).ToString("c"))</span>
					</li>
				}

				<li class="list-group-item d-flex justify-content-between bg-light">
					<small class="text-info">Total</small>
					<strong class="text-info">@Model.Order.Total.ToString("c")</strong>
				</li>
			</ul>
		</div>
	</div>
</div>

ParrotdiseShop.Web/Areas/Customer/Views/ShoppingCartItems/Summary.cshtml
@{
	ViewData["Title"] = "Summary";
}


<form method="post">
<div class="card shadow border-0 mt-4">
		<div class="card-header bg-secondary bg-gradient text-light py-4">
			<div class="row">
				<div class="col-12 text-center">
					<h3 class="text-white text-uppercase">
						Shopping Cart
					</h3>
				</div>
			</div>
		</div>
			<div class="card-body">
				<div class="row pb-4">
						<div class="col-12 text-end">
							<a class="btn btn-outline-secondary fw-bold text-uppercase btn-sm">Back to Cart</a>
						</div>
					</div>
				<div class="row">
						<div class="col-12 col-lg-6 pb-2">
							<div class="row">
								<h4 class="d-flex justify-content-between align-items-center mb-3">
									<span class="text-info">Shipping Details:</span>
								</h4>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Name</label>
								</div>
								<div class="col-9">
									<input class="form-control" />
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Phone</label>
								</div>
								<div class="col-9">
									<input class="form-control" />
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Street Address</label>
								</div>
								<div class="col-9">
									<input class="form-control" />
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>City</label>
								</div>
								<div class="col-9">
									<input class="form-control" />
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>State</label>
								</div>
								<div class="col-9">
									<input class="form-control" />
								</div>
							</div>
							<div class="row my-1">
								<div class="col-3">
									<label>Postal Code</label>
								</div>
								<div class="col-9">
									<input class="form-control" />
								</div>
							</div>
						</div>
						<div class="col-12 col-lg-5 offset-lg-1">
							<h4 class="d-flex justify-content-between align-items-center mb-3">
								<span class="text-info">Order Summary:</span>
							</h4>
							<ul class="list-group mb-3">
								<li class="list-group-item d-flex justify-content-between">
									<div>
										<h6 class="my-0">Title</h6>
										<small class="text-muted">Quantity: Count</small>
									</div>
									<span class="text-muted">Price * Count </span>
								</li>


								<li class="list-group-item d-flex justify-content-between bg-light">
									<small class="text-info">Total</small>
									<strong class="text-info">$$</strong>
								</li>
							</ul>
						</div>
					</div>
			</div>
			<div class="card-footer bg-white border-0 p-0 pe-4">
				<div class="row">
					<div class="col-3 offset-9 mb-3">
						<button type="submit" value="Place Order" class="btn btn-primary form-control text-uppercase fw-semibold bg-gradient">Place Order</button>
					</div>
				</div>
		</div>
		</div>
</form>